### ISSUE TITLE
Deploy documentation site

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork.github.io#15]
Configure Travis or  Github Actions to deploy the site.

**Comment by cristianoc72** [comment]
MkDocs documentation recommends two repositories: one containing the markdown and one to deploy the compiled site by `gh-deploy` pluging.

We could use `mkdocs` branch for markdown and `master` branch to deploy.
I'm thinking about using Github Actions to do the work.

**Comment by gossi** [comment]
sounds good to me 👍 go ahead!

**Comment by cristianoc72** [comment]
New documentation site is out!
I added [this paragraph](http://phootwork.github.io/docs_contributing/#branch-strategy) to describe the branch strategy. I also updated the links to api docs.

See https://github.com/phootwork/phootwork.github.io/blob/mkdocs/.github/workflows/deploy.yml if you're interested in Github Actions workflow to build and deploy the site.

**Comment by gossi** [comment]
This is amazing!!!

I changed the `default` branch of this repo to `mkdocs` as this is what I expect when navigating here and also where all PRs should be directed to!

**Comment by cristianoc72** [comment]
Sure! I forgot it.
