### ISSUE TITLE
Api documentation

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork.github.io#16]
Adjust https://github.com/phootwork/phootwork/blob/master/sami.php to build the documentation api into docs/api instead of api directory.

**Comment by cristianoc72** [comment]
After some tests,I realized that it could be better if we decouple our api documentation from mkdocs repository.
Well, it works fine also leaving  everything as is, in fact mkdocs copy-paste all api html files into the compiled repository, but mixing up documents written by hand with documents written by bot could cause some tedious problems.

I.e.: Sami generates two files called `text.html`, which describes the content of `src/lang/text` directory, and `Text.html` containing the api of `phootwork\lang\Text` class. No  problem with Github Pages, but if you develop under Windows (or other SO with case-insensitive file system) the two files conflict and git asks you to fix it, every time you pull from the repository. And even if you fix it, this conflict appears again each time the bot deploys the api.

Since Sami generates a standalone site, I'ld like to create a new repository under phootwork organization (called `api`) and push there the auto-generated api, on `gh-pages` branch, which'll have  `https://phootwork.github.io/api` address.

@gossi wdta?

**Comment by gossi** [comment]
yeah, I had this case-insensitive problem, too - on my mac (btw `git config ignorecase false`) but you also see some weird commits from my side.

I like your idea with the new repo, do it 👍

**Comment by cristianoc72** [comment]
Done. See https://phootwork.github.io/api and https://github.com/phootwork/phootwork/blob/master/.github/workflows/api.yml if you are interested in Github Actions workflow to generate it.
