### ISSUE TITLE
Website technology

### ISSUE THREAD

**Issue by gossi** [phootwork/phootwork.github.io#6]
So far, the website is written in markdown on jekyll. I love the simplicity of markdown but jekyll is not very supportive to be honest. So here are some options:

- **Jekyll** (current) - just stay with it.
- **[MkDocs](https://www.mkdocs.org/)** - Markdown but without the hassle of jekyll
- **ReadTheDocs** - something with is using RST for writing, but I found RST not as much as simplistic in comparison to just markdown (I did php-code-generator with it, it's not that easy to maintain)
- **Custom** - I'll do ember for work. Could spin something up, that's similar to MkDocs, yet still harder to do - I'm also against this.

My vote would be to look into mkdocs.

**Comment by cristianoc72** [comment]
I'm giving a try to MkDocs and it looks so cool!!

**Comment by cristianoc72** [comment]
After some tests, I'm definitely for MkDocs!
@gossi since you're a frontend expert, could you think about a theme? Imho, we could also choose one from here https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes

**Comment by gossi** [comment]
Cool to here. I won't find time for a theme but happy with the choices over there. For me: `Cinder`, `Bootswatch` and `Ivory` look best. Do we have a match here? 😉

**Comment by cristianoc72** [comment]
:rofl: no match here! Choose one between `Cinder` and `Ivory` and it's good for me (Bootswatch seems less actively maintained).

**Comment by gossi** [comment]
What are your favorites?

**Comment by cristianoc72** [comment]
My vote for `Cinder`

**Comment by gossi** [comment]
We have a winner 🎉 😂

**Comment by cristianoc72** [comment]
🍷 🍷

**Comment by gossi** [comment]
mkdocs is the way to go. Looking good. I close this one.
